var all_data = {
    "1762": {
        "unknown": 1
    }, 
    "1790": {
        "fireball": 1
    }, 
    "1860": {
        "fireball": 1
    }, 
    "1864": {
        "unknown": 1
    }, 
    "1865": {
        "unknown": 1
    }, 
    "1871": {
        "egg": 1
    }, 
    "1880": {
        "fireball": 1
    }, 
    "1896": {
        "formation": 1
    }, 
    "1897": {
        "unknown": 1
    }, 
    "1899": {
        "sphere": 1
    }, 
    "1901": {
        "unknown": 1
    }, 
    "1905": {
        "circle": 1
    }, 
    "1906": {
        "other": 1
    }, 
    "1910": {
        "disk": 1, 
        "unknown": 1, 
        "cigar": 1
    }, 
    "1400": {
        "circle": 1
    }, 
    "1914": {
        "unknown": 1
    }, 
    "1916": {
        "cigar": 1
    }, 
    "1920": {
        "unknown": 2
    }, 
    "1922": {
        "unknown": 1
    }, 
    "1925": {
        "disk": 1
    }, 
    "1929": {
        "disk": 1
    }, 
    "1930": {
        "other": 1, 
        "triangle": 1
    }, 
    "1931": {
        "oval": 1, 
        "disk": 1
    }, 
    "1933": {
        "light": 1
    }, 
    "1934": {
        "disk": 1
    }, 
    "1935": {
        "circle": 1
    }, 
    "1936": {
        "disk": 1, 
        "cigar": 1, 
        "rectangle": 1
    }, 
    "1937": {
        "light": 1, 
        "cylinder": 1
    }, 
    "1939": {
        "oval": 1, 
        "sphere": 1
    }, 
    "1941": {
        "circle": 1, 
        "disk": 1, 
        "other": 1
    }, 
    "1942": {
        "unknown": 2, 
        "disk": 2, 
        "rectangle": 1
    }, 
    "1943": {
        "cylinder": 1, 
        "light": 2, 
        "cigar": 1, 
        "sphere": 1, 
        "other": 1, 
        "unknown": 1, 
        "disk": 1
    }, 
    "1944": {
        "disk": 6, 
        "sphere": 1, 
        "cylinder": 1, 
        "cigar": 3, 
        "circle": 1
    }, 
    "1945": {
        "cigar": 1, 
        "sphere": 2, 
        "formation": 1, 
        "oval": 1, 
        "circle": 2, 
        "disk": 5
    }, 
    "1946": {
        "cigar": 1, 
        "unknown": 1, 
        "flash": 1, 
        "sphere": 2, 
        "formation": 1, 
        "oval": 1, 
        "disk": 3, 
        "fireball": 1
    }, 
    "1947": {
        "cylinder": 1, 
        "triangle": 1, 
        "unknown": 8, 
        "cigar": 3, 
        "other": 3, 
        "formation": 2, 
        "chevron": 1, 
        "light": 2, 
        "oval": 2, 
        "circle": 4, 
        "disk": 12
    }, 
    "1948": {
        "disk": 1, 
        "unknown": 1, 
        "sphere": 1, 
        "light": 1, 
        "oval": 2, 
        "circle": 2, 
        "fireball": 1, 
        "rectangle": 1
    }, 
    "1949": {
        "cylinder": 1, 
        "light": 3, 
        "cigar": 2, 
        "other": 1, 
        "formation": 1, 
        "unknown": 1, 
        "circle": 3, 
        "disk": 4
    }, 
    "1950": {
        "triangle": 2, 
        "light": 3, 
        "cigar": 1, 
        "sphere": 2, 
        "other": 1, 
        "formation": 1, 
        "unknown": 3, 
        "oval": 4, 
        "circle": 1, 
        "disk": 10
    }, 
    "1951": {
        "unknown": 2, 
        "cigar": 4, 
        "sphere": 1, 
        "oval": 2, 
        "circle": 2, 
        "disk": 12
    }, 
    "1952": {
        "cylinder": 3, 
        "fireball": 1, 
        "triangle": 2, 
        "unknown": 4, 
        "cigar": 2, 
        "sphere": 5, 
        "other": 5, 
        "light": 3, 
        "oval": 5, 
        "circle": 6, 
        "disk": 15, 
        "egg": 1
    }, 
    "1953": {
        "cylinder": 1, 
        "fireball": 4, 
        "unknown": 5, 
        "cigar": 3, 
        "sphere": 2, 
        "other": 3, 
        "chevron": 1, 
        "light": 2, 
        "oval": 2, 
        "circle": 3, 
        "disk": 9
    }, 
    "1954": {
        "cylinder": 1, 
        "diamond": 1, 
        "triangle": 1, 
        "light": 6, 
        "cigar": 2, 
        "other": 3, 
        "formation": 1, 
        "chevron": 1, 
        "unknown": 4, 
        "oval": 4, 
        "changing": 1, 
        "circle": 8, 
        "disk": 18, 
        "rectangle": 1, 
        "fireball": 1
    }, 
    "1955": {
        "fireball": 5, 
        "light": 9, 
        "cigar": 3, 
        "formation": 1, 
        "unknown": 2, 
        "oval": 1, 
        "circle": 6, 
        "disk": 9, 
        "egg": 2
    }, 
    "1956": {
        "cylinder": 1, 
        "cigar": 5, 
        "light": 6, 
        "flash": 1, 
        "sphere": 2, 
        "other": 4, 
        "unknown": 4, 
        "oval": 1, 
        "circle": 8, 
        "disk": 8, 
        "rectangle": 2
    }, 
    "1957": {
        "cylinder": 2, 
        "fireball": 4, 
        "triangle": 3, 
        "light": 9, 
        "diamond": 2, 
        "cigar": 11, 
        "sphere": 3, 
        "other": 3, 
        "formation": 2, 
        "teardrop": 1, 
        "unknown": 9, 
        "oval": 3, 
        "circle": 2, 
        "disk": 19, 
        "rectangle": 1
    }, 
    "1958": {
        "fireball": 3, 
        "triangle": 1, 
        "unknown": 4, 
        "diamond": 2, 
        "cigar": 4, 
        "sphere": 2, 
        "other": 2, 
        "teardrop": 1, 
        "light": 5, 
        "oval": 4, 
        "circle": 4, 
        "disk": 13
    }, 
    "1959": {
        "cylinder": 2, 
        "fireball": 1, 
        "light": 8, 
        "cigar": 3, 
        "sphere": 3, 
        "other": 4, 
        "formation": 2, 
        "unknown": 7, 
        "oval": 3, 
        "circle": 5, 
        "disk": 11, 
        "egg": 1, 
        "rectangle": 1
    }, 
    "1960": {
        "cylinder": 1, 
        "fireball": 1, 
        "triangle": 2, 
        "unknown": 6, 
        "diamond": 1, 
        "cigar": 6, 
        "sphere": 5, 
        "other": 10, 
        "formation": 2, 
        "light": 3, 
        "oval": 6, 
        "changing": 1, 
        "circle": 7, 
        "disk": 16
    }, 
    "1961": {
        "cylinder": 1, 
        "diamond": 1, 
        "triangle": 2, 
        "light": 5, 
        "cigar": 4, 
        "sphere": 6, 
        "teardrop": 1, 
        "unknown": 4, 
        "changing": 1, 
        "circle": 7, 
        "disk": 11, 
        "egg": 1
    }, 
    "1962": {
        "cylinder": 2, 
        "diamond": 1, 
        "light": 6, 
        "cigar": 2, 
        "sphere": 6, 
        "other": 5, 
        "chevron": 1, 
        "unknown": 7, 
        "oval": 4, 
        "changing": 2, 
        "circle": 5, 
        "disk": 18, 
        "rectangle": 1
    }, 
    "1963": {
        "cylinder": 1, 
        "triangle": 5, 
        "light": 8, 
        "cigar": 6, 
        "sphere": 4, 
        "other": 8, 
        "formation": 2, 
        "chevron": 1, 
        "unknown": 9, 
        "oval": 4, 
        "circle": 6, 
        "disk": 24, 
        "rectangle": 1
    }, 
    "1964": {
        "cylinder": 1, 
        "fireball": 4, 
        "triangle": 2, 
        "light": 14, 
        "diamond": 1, 
        "cigar": 5, 
        "cross": 1, 
        "sphere": 5, 
        "other": 5, 
        "formation": 2, 
        "unknown": 8, 
        "oval": 2, 
        "changing": 1, 
        "circle": 9, 
        "disk": 24
    }, 
    "1965": {
        "flash": 1, 
        "cylinder": 5, 
        "fireball": 11, 
        "triangle": 6, 
        "light": 23, 
        "cigar": 11, 
        "sphere": 17, 
        "other": 6, 
        "formation": 2, 
        "unknown": 17, 
        "oval": 16, 
        "changing": 3, 
        "circle": 13, 
        "disk": 39, 
        "egg": 7, 
        "rectangle": 1
    }, 
    "1966": {
        "flash": 1, 
        "cylinder": 1, 
        "diamond": 3, 
        "triangle": 10, 
        "light": 17, 
        "cigar": 11, 
        "sphere": 11, 
        "other": 13, 
        "formation": 1, 
        "chevron": 5, 
        "unknown": 19, 
        "oval": 15, 
        "circle": 15, 
        "disk": 58, 
        "egg": 3, 
        "rectangle": 2, 
        "fireball": 1
    }, 
    "1967": {
        "cylinder": 3, 
        "disk": 40, 
        "triangle": 8, 
        "unknown": 18, 
        "diamond": 1, 
        "cigar": 18, 
        "sphere": 10, 
        "teardrop": 4, 
        "formation": 5, 
        "chevron": 5, 
        "light": 29, 
        "oval": 11, 
        "changing": 3, 
        "circle": 21, 
        "fireball": 5, 
        "other": 13
    }, 
    "1968": {
        "flash": 2, 
        "cylinder": 2, 
        "diamond": 3, 
        "triangle": 10, 
        "light": 25, 
        "cigar": 17, 
        "sphere": 13, 
        "other": 10, 
        "formation": 4, 
        "cone": 1, 
        "unknown": 13, 
        "oval": 11, 
        "changing": 3, 
        "circle": 29, 
        "disk": 54, 
        "egg": 2, 
        "rectangle": 2, 
        "fireball": 8
    }, 
    "1969": {
        "cylinder": 5, 
        "flash": 1, 
        "triangle": 9, 
        "unknown": 14, 
        "cigar": 13, 
        "cross": 1, 
        "sphere": 14, 
        "other": 16, 
        "formation": 7, 
        "cone": 1, 
        "light": 15, 
        "oval": 9, 
        "changing": 1, 
        "circle": 14, 
        "disk": 29, 
        "egg": 1, 
        "rectangle": 1, 
        "fireball": 2
    }, 
    "1970": {
        "cylinder": 3, 
        "diamond": 1, 
        "triangle": 2, 
        "light": 20, 
        "cigar": 1, 
        "sphere": 11, 
        "other": 11, 
        "chevron": 1, 
        "unknown": 16, 
        "oval": 14, 
        "changing": 1, 
        "circle": 9, 
        "disk": 43, 
        "egg": 4, 
        "rectangle": 3, 
        "fireball": 2
    }, 
    "1971": {
        "cylinder": 1, 
        "diamond": 2, 
        "triangle": 9, 
        "cone": 1, 
        "unknown": 6, 
        "flash": 1, 
        "cross": 1, 
        "sphere": 6, 
        "other": 5, 
        "formation": 3, 
        "teardrop": 1, 
        "chevron": 2, 
        "light": 13, 
        "oval": 9, 
        "circle": 18, 
        "disk": 37, 
        "cigar": 8, 
        "fireball": 1
    }, 
    "1972": {
        "cylinder": 5, 
        "fireball": 4, 
        "triangle": 10, 
        "light": 29, 
        "diamond": 1, 
        "cigar": 8, 
        "sphere": 10, 
        "other": 11, 
        "formation": 2, 
        "teardrop": 2, 
        "chevron": 3, 
        "unknown": 16, 
        "oval": 10, 
        "circle": 24, 
        "disk": 34, 
        "egg": 1, 
        "rectangle": 2
    }, 
    "1973": {
        "flash": 1, 
        "cylinder": 5, 
        "diamond": 3, 
        "triangle": 15, 
        "unknown": 19, 
        "cigar": 15, 
        "sphere": 16, 
        "other": 11, 
        "formation": 2, 
        "cone": 1, 
        "chevron": 2, 
        "light": 23, 
        "oval": 19, 
        "changing": 2, 
        "circle": 23, 
        "disk": 53, 
        "egg": 1, 
        "rectangle": 3, 
        "fireball": 8
    }, 
    "1974": {
        "flash": 1, 
        "cylinder": 4, 
        "fireball": 9, 
        "triangle": 22, 
        "light": 28, 
        "diamond": 1, 
        "cigar": 15, 
        "unknown": 24, 
        "cross": 1, 
        "sphere": 19, 
        "other": 18, 
        "teardrop": 1, 
        "chevron": 3, 
        "delta": 1, 
        "oval": 20, 
        "changing": 3, 
        "circle": 29, 
        "disk": 61, 
        "egg": 1, 
        "rectangle": 5, 
        "cone": 1
    }, 
    "1975": {
        "cylinder": 4, 
        "cigar": 24, 
        "triangle": 24, 
        "teardrop": 2, 
        "unknown": 24, 
        "diamond": 1, 
        "flash": 2, 
        "sphere": 19, 
        "other": 17, 
        "cone": 3, 
        "chevron": 2, 
        "light": 40, 
        "oval": 19, 
        "changing": 3, 
        "circle": 34, 
        "disk": 73, 
        "egg": 1, 
        "rectangle": 8, 
        "fireball": 8
    }, 
    "1976": {
        "rectangle": 11, 
        "cylinder": 3, 
        "diamond": 2, 
        "triangle": 19, 
        "light": 34, 
        "flash": 3, 
        "cross": 1, 
        "sphere": 14, 
        "other": 16, 
        "formation": 7, 
        "teardrop": 2, 
        "chevron": 1, 
        "unknown": 29, 
        "oval": 18, 
        "changing": 6, 
        "circle": 21, 
        "disk": 62, 
        "egg": 2, 
        "cigar": 13, 
        "fireball": 9
    }, 
    "1977": {
        "flash": 3, 
        "cylinder": 3, 
        "diamond": 3, 
        "triangle": 31, 
        "unknown": 23, 
        "cigar": 17, 
        "sphere": 16, 
        "other": 13, 
        "formation": 4, 
        "cone": 1, 
        "chevron": 9, 
        "light": 30, 
        "oval": 16, 
        "changing": 3, 
        "circle": 23, 
        "disk": 54, 
        "egg": 3, 
        "rectangle": 5, 
        "fireball": 4
    }, 
    "1978": {
        "cylinder": 6, 
        "flash": 2, 
        "triangle": 27, 
        "cone": 1, 
        "light": 42, 
        "diamond": 3, 
        "cigar": 13, 
        "sphere": 28, 
        "other": 25, 
        "formation": 6, 
        "teardrop": 1, 
        "chevron": 2, 
        "unknown": 25, 
        "oval": 29, 
        "changing": 4, 
        "circle": 28, 
        "disk": 74, 
        "egg": 2, 
        "rectangle": 10, 
        "fireball": 10
    }, 
    "1979": {
        "cylinder": 4, 
        "fireball": 7, 
        "triangle": 33, 
        "unknown": 18, 
        "diamond": 1, 
        "flash": 1, 
        "cross": 2, 
        "sphere": 8, 
        "other": 26, 
        "formation": 3, 
        "teardrop": 2, 
        "chevron": 3, 
        "light": 30, 
        "oval": 10, 
        "changing": 4, 
        "circle": 26, 
        "disk": 45, 
        "cigar": 8, 
        "egg": 2, 
        "rectangle": 13
    }, 
    "1980": {
        "cylinder": 6, 
        "diamond": 5, 
        "triangle": 19, 
        "light": 31, 
        "cigar": 13, 
        "sphere": 14, 
        "other": 22, 
        "formation": 4, 
        "teardrop": 1, 
        "chevron": 3, 
        "unknown": 23, 
        "oval": 13, 
        "changing": 5, 
        "circle": 13, 
        "disk": 47, 
        "egg": 5, 
        "rectangle": 9, 
        "fireball": 3
    }, 
    "1981": {
        "cylinder": 3, 
        "fireball": 5, 
        "triangle": 13, 
        "light": 18, 
        "diamond": 4, 
        "cigar": 12, 
        "sphere": 10, 
        "other": 14, 
        "formation": 4, 
        "cone": 2, 
        "chevron": 2, 
        "unknown": 18, 
        "oval": 9, 
        "changing": 3, 
        "circle": 9, 
        "disk": 25, 
        "egg": 1, 
        "rectangle": 6
    }, 
    "1982": {
        "flash": 1, 
        "cylinder": 5, 
        "fireball": 5, 
        "triangle": 17, 
        "light": 27, 
        "diamond": 3, 
        "cigar": 8, 
        "sphere": 12, 
        "other": 11, 
        "formation": 5, 
        "teardrop": 2, 
        "chevron": 5, 
        "unknown": 14, 
        "oval": 10, 
        "changing": 2, 
        "circle": 16, 
        "disk": 42, 
        "egg": 2, 
        "rectangle": 4, 
        "cone": 1
    }, 
    "1983": {
        "flash": 1, 
        "cylinder": 2, 
        "diamond": 6, 
        "triangle": 19, 
        "unknown": 14, 
        "cigar": 4, 
        "sphere": 12, 
        "other": 16, 
        "formation": 4, 
        "chevron": 1, 
        "light": 9, 
        "oval": 12, 
        "changing": 3, 
        "circle": 7, 
        "disk": 31, 
        "egg": 2, 
        "rectangle": 1, 
        "fireball": 6
    }, 
    "1984": {
        "cylinder": 4, 
        "diamond": 3, 
        "triangle": 26, 
        "teardrop": 1, 
        "unknown": 18, 
        "cigar": 8, 
        "sphere": 13, 
        "other": 18, 
        "formation": 5, 
        "cone": 1, 
        "chevron": 3, 
        "light": 22, 
        "oval": 6, 
        "changing": 2, 
        "circle": 24, 
        "disk": 18, 
        "egg": 4, 
        "rectangle": 5, 
        "fireball": 7
    }, 
    "1985": {
        "flash": 1, 
        "cylinder": 3, 
        "diamond": 4, 
        "triangle": 28, 
        "light": 18, 
        "cigar": 8, 
        "sphere": 15, 
        "other": 22, 
        "formation": 7, 
        "teardrop": 1, 
        "chevron": 5, 
        "unknown": 15, 
        "oval": 14, 
        "changing": 5, 
        "circle": 19, 
        "disk": 30, 
        "egg": 4, 
        "rectangle": 4, 
        "fireball": 3
    }, 
    "1986": {
        "cylinder": 3, 
        "fireball": 4, 
        "triangle": 37, 
        "unknown": 18, 
        "diamond": 6, 
        "cigar": 6, 
        "sphere": 14, 
        "other": 23, 
        "formation": 5, 
        "cone": 1, 
        "chevron": 6, 
        "light": 18, 
        "oval": 11, 
        "changing": 2, 
        "circle": 13, 
        "disk": 24, 
        "egg": 1, 
        "rectangle": 6
    }, 
    "1987": {
        "flash": 4, 
        "cylinder": 4, 
        "disk": 27, 
        "triangle": 27, 
        "unknown": 24, 
        "diamond": 2, 
        "cigar": 10, 
        "sphere": 13, 
        "other": 22, 
        "formation": 6, 
        "cone": 1, 
        "chevron": 7, 
        "light": 32, 
        "oval": 7, 
        "changing": 5, 
        "circle": 10, 
        "fireball": 7, 
        "egg": 3, 
        "rectangle": 8
    }, 
    "1988": {
        "cylinder": 6, 
        "fireball": 6, 
        "triangle": 20, 
        "cigar": 6, 
        "unknown": 24, 
        "diamond": 4, 
        "flash": 1, 
        "cross": 2, 
        "sphere": 21, 
        "other": 17, 
        "formation": 5, 
        "cone": 2, 
        "chevron": 5, 
        "light": 26, 
        "oval": 13, 
        "changing": 6, 
        "circle": 24, 
        "disk": 27, 
        "egg": 4, 
        "rectangle": 6
    }, 
    "1989": {
        "cylinder": 5, 
        "flash": 2, 
        "triangle": 35, 
        "light": 21, 
        "diamond": 3, 
        "cigar": 7, 
        "sphere": 22, 
        "other": 24, 
        "formation": 6, 
        "teardrop": 2, 
        "chevron": 5, 
        "unknown": 27, 
        "oval": 10, 
        "changing": 5, 
        "circle": 16, 
        "disk": 35, 
        "egg": 5, 
        "rectangle": 11, 
        "fireball": 8
    }, 
    "1990": {
        "flash": 3, 
        "cylinder": 2, 
        "disk": 27, 
        "triangle": 34, 
        "unknown": 29, 
        "diamond": 2, 
        "cigar": 7, 
        "sphere": 15, 
        "other": 30, 
        "formation": 6, 
        "teardrop": 3, 
        "chevron": 4, 
        "light": 43, 
        "oval": 19, 
        "changing": 3, 
        "circle": 15, 
        "fireball": 10, 
        "egg": 1, 
        "rectangle": 3
    }, 
    "1991": {
        "flash": 1, 
        "cylinder": 4, 
        "fireball": 2, 
        "triangle": 40, 
        "light": 40, 
        "diamond": 2, 
        "cigar": 6, 
        "sphere": 11, 
        "other": 26, 
        "formation": 6, 
        "teardrop": 2, 
        "unknown": 18, 
        "oval": 8, 
        "changing": 3, 
        "circle": 20, 
        "disk": 33, 
        "egg": 6, 
        "rectangle": 7
    }, 
    "1992": {
        "flash": 4, 
        "cylinder": 1, 
        "fireball": 10, 
        "triangle": 31, 
        "light": 33, 
        "diamond": 4, 
        "cigar": 10, 
        "cross": 1, 
        "sphere": 22, 
        "other": 17, 
        "formation": 9, 
        "teardrop": 1, 
        "chevron": 2, 
        "unknown": 30, 
        "oval": 19, 
        "changing": 5, 
        "circle": 21, 
        "disk": 26, 
        "egg": 5, 
        "rectangle": 6, 
        "cone": 2
    }, 
    "1993": {
        "flash": 2, 
        "cylinder": 5, 
        "fireball": 8, 
        "triangle": 59, 
        "unknown": 29, 
        "diamond": 5, 
        "cigar": 13, 
        "cross": 1, 
        "sphere": 24, 
        "delta": 1, 
        "other": 37, 
        "formation": 11, 
        "teardrop": 4, 
        "chevron": 3, 
        "light": 46, 
        "oval": 15, 
        "changing": 2, 
        "circle": 26, 
        "disk": 25, 
        "egg": 4, 
        "rectangle": 8
    }, 
    "1994": {
        "cylinder": 3, 
        "fireball": 17, 
        "triangle": 72, 
        "cigar": 9, 
        "unknown": 49, 
        "diamond": 3, 
        "flash": 8, 
        "light": 61, 
        "sphere": 29, 
        "other": 33, 
        "formation": 5, 
        "teardrop": 2, 
        "chevron": 7, 
        "delta": 1, 
        "oval": 22, 
        "changing": 10, 
        "circle": 31, 
        "disk": 46, 
        "egg": 5, 
        "rectangle": 10
    }, 
    "1995": {
        "cylinder": 4, 
        "sphere": 29, 
        "cone": 6, 
        "chevron": 10, 
        "oval": 24, 
        "disk": 47, 
        "unknown": 891, 
        "flash": 5, 
        "cross": 2, 
        "teardrop": 4, 
        "circle": 41, 
        "rectangle": 8, 
        "diamond": 8, 
        "triangle": 79, 
        "cigar": 14, 
        "formation": 15, 
        "delta": 1, 
        "changing": 15, 
        "light": 104, 
        "round": 1, 
        "fireball": 32, 
        "egg": 4, 
        "other": 49
    }, 
    "1996": {
        "cylinder": 14, 
        "sphere": 34, 
        "cone": 3, 
        "chevron": 4, 
        "oval": 28, 
        "disk": 61, 
        "unknown": 357, 
        "flash": 4, 
        "cross": 4, 
        "teardrop": 7, 
        "circle": 38, 
        "rectangle": 13, 
        "diamond": 19, 
        "triangle": 109, 
        "cigar": 7, 
        "dome": 1, 
        "formation": 15, 
        "changing": 8, 
        "light": 131, 
        "changed": 1, 
        "round": 1, 
        "fireball": 24, 
        "egg": 6, 
        "other": 51
    }, 
    "1997": {
        "cylinder": 18, 
        "pyramid": 1, 
        "sphere": 81, 
        "cone": 3, 
        "chevron": 28, 
        "oval": 50, 
        "disk": 96, 
        "unknown": 107, 
        "flash": 8, 
        "cross": 3, 
        "teardrop": 9, 
        "circle": 75, 
        "rectangle": 19, 
        "diamond": 19, 
        "triangle": 195, 
        "cigar": 34, 
        "formation": 71, 
        "delta": 4, 
        "changing": 16, 
        "hexagon": 1, 
        "light": 289, 
        "flare": 1, 
        "fireball": 50, 
        "egg": 11, 
        "other": 146, 
        "crescent": 2
    }, 
    "1998": {
        "cylinder": 35, 
        "flash": 40, 
        "triangle": 207, 
        "cone": 15, 
        "light": 366, 
        "diamond": 29, 
        "cigar": 46, 
        "cross": 5, 
        "sphere": 153, 
        "other": 146, 
        "formation": 59, 
        "teardrop": 14, 
        "chevron": 18, 
        "unknown": 112, 
        "oval": 79, 
        "changing": 51, 
        "circle": 145, 
        "disk": 130, 
        "egg": 27, 
        "rectangle": 18, 
        "fireball": 246
    }, 
    "1999": {
        "cylinder": 56, 
        "sphere": 186, 
        "cone": 10, 
        "chevron": 50, 
        "oval": 106, 
        "disk": 193, 
        "unknown": 293, 
        "flash": 57, 
        "cross": 5, 
        "teardrop": 35, 
        "circle": 242, 
        "rectangle": 39, 
        "diamond": 42, 
        "triangle": 294, 
        "cigar": 90, 
        "Duration:3 min seen in the distance, lights that went around the craft in a strob,circeler around it. was hovering for about 3 min&apos;s and went stright up and disaperd.seen in the distance, lights that went around the craft in a strob,circeler around it. was hovering for about 3 min&apos;s and went stright up and disaperd.((NUFORC Note:  We wonder whether the witness might have observed an advertising light.  We assume the sighting occurred near the residence of the witness, and have entered that location above.  PD))": 1, 
        "formation": 93, 
        "changing": 80, 
        "light": 573, 
        "fireball": 316, 
        "egg": 40, 
        "other": 265
    }, 
    "2000": {
        "cylinder": 56, 
        "cigar": 80, 
        "triangle": 329, 
        "light": 598, 
        "diamond": 56, 
        "flash": 46, 
        "cross": 11, 
        "disk": 202, 
        "sphere": 148, 
        "teardrop": 27, 
        "formation": 83, 
        "cone": 15, 
        "chevron": 40, 
        "unknown": 281, 
        "oval": 131, 
        "changing": 78, 
        "circle": 264, 
        "fireball": 233, 
        "egg": 46, 
        "other": 240, 
        "rectangle": 44
    }, 
    "2001": {
        "flash": 53, 
        "cylinder": 50, 
        "diamond": 74, 
        "triangle": 362, 
        "light": 730, 
        "cigar": 100, 
        "cross": 9, 
        "disk": 228, 
        "sphere": 177, 
        "other": 266, 
        "formation": 125, 
        "teardrop": 38, 
        "chevron": 50, 
        "unknown": 302, 
        "oval": 170, 
        "changing": 92, 
        "circle": 270, 
        "fireball": 210, 
        "egg": 46, 
        "rectangle": 58, 
        "cone": 25
    }, 
    "2002": {
        "cylinder": 65, 
        "flash": 72, 
        "triangle": 365, 
        "unknown": 387, 
        "diamond": 62, 
        "cigar": 83, 
        "cross": 14, 
        "disk": 259, 
        "sphere": 195, 
        "other": 274, 
        "formation": 102, 
        "teardrop": 47, 
        "chevron": 66, 
        "light": 722, 
        "oval": 153, 
        "changing": 112, 
        "circle": 306, 
        "fireball": 194, 
        "egg": 53, 
        "rectangle": 56, 
        "cone": 21
    }, 
    "2003": {
        "cylinder": 83, 
        "sphere": 246, 
        "cone": 18, 
        "chevron": 56, 
        "oval": 225, 
        "disk": 293, 
        "Duration:45 min this is the third time i have seen these objects in less than a month in this area after the first time i was so scared that i wasn&apos;t sure if i had seen what i was sure i saw.....but since that first time i have been driven to try and explain what i have been seeing..so a friend and i went to the same spot where we saw the onject the first time and there it was two objects this time.....they were round with glowing light beams coming out of them it changed shapes and moved in a zig zag formaton i have a video a very clear video....it moved and we were able to follow it for over 50 miles. on the video you can see clearly that the beams change colors....the object changes shape...it moves very fast and makes no sound....i&apos;m not crazy...i need to talk to someone who knows what i am talking about, i want someone to look at this video.((NUFORC Note:  We would be happy to look at the video, and will request a copy.  PD))": 1, 
        "unknown": 453, 
        "flash": 82, 
        "cross": 19, 
        "teardrop": 51, 
        "circle": 366, 
        "rectangle": 60, 
        "diamond": 66, 
        "triangle": 403, 
        "cigar": 118, 
        "formation": 130, 
        "changing": 115, 
        "light": 931, 
        "fireball": 210, 
        "egg": 59, 
        "other": 351
    }, 
    "2004": {
        "flash": 80, 
        "cylinder": 69, 
        "fireball": 214, 
        "triangle": 489, 
        "unknown": 467, 
        "diamond": 75, 
        "cigar": 114, 
        "cross": 17, 
        "sphere": 283, 
        "other": 379, 
        "formation": 160, 
        "teardrop": 45, 
        "chevron": 61, 
        "light": 1043, 
        "oval": 209, 
        "changing": 134, 
        "circle": 365, 
        "disk": 324, 
        "egg": 60, 
        "rectangle": 51, 
        "cone": 18
    }, 
    "2005": {
        "cylinder": 73, 
        "diamond": 64, 
        "triangle": 462, 
        "cone": 19, 
        "unknown": 442, 
        "flash": 93, 
        "cross": 13, 
        "sphere": 236, 
        "other": 365, 
        "formation": 136, 
        "teardrop": 43, 
        "chevron": 53, 
        "light": 960, 
        "oval": 185, 
        "changing": 139, 
        "circle": 384, 
        "disk": 288, 
        "cigar": 118, 
        "egg": 40, 
        "rectangle": 59, 
        "fireball": 233
    }, 
    "2006": {
        "flash": 80, 
        "cylinder": 61, 
        "diamond": 61, 
        "triangle": 395, 
        "unknown": 430, 
        "cigar": 114, 
        "cross": 12, 
        "disk": 272, 
        "sphere": 240, 
        "teardrop": 49, 
        "formation": 119, 
        "cone": 15, 
        "chevron": 40, 
        "light": 818, 
        "oval": 199, 
        "changing": 128, 
        "circle": 380, 
        "fireball": 228, 
        "egg": 40, 
        "other": 295, 
        "rectangle": 75
    }, 
    "2007": {
        "flash": 75, 
        "cylinder": 74, 
        "fireball": 233, 
        "triangle": 470, 
        "teardrop": 53, 
        "light": 1017, 
        "diamond": 63, 
        "cigar": 145, 
        "cross": 9, 
        "sphere": 271, 
        "other": 315, 
        "formation": 149, 
        "cone": 20, 
        "chevron": 49, 
        "unknown": 465, 
        "oval": 232, 
        "changing": 107, 
        "circle": 457, 
        "disk": 281, 
        "egg": 30, 
        "rectangle": 88
    }, 
    "2008": {
        "rectangle": 87, 
        "cylinder": 85, 
        "disk": 295, 
        "triangle": 510, 
        "unknown": 525, 
        "diamond": 82, 
        "flash": 97, 
        "cross": 17, 
        "sphere": 322, 
        "other": 332, 
        "formation": 166, 
        "teardrop": 56, 
        "chevron": 70, 
        "light": 1102, 
        "oval": 273, 
        "changing": 155, 
        "circle": 454, 
        "fireball": 277, 
        "egg": 56, 
        "cigar": 141, 
        "cone": 21
    }, 
    "2009": {
        "cylinder": 68, 
        "fireball": 271, 
        "triangle": 426, 
        "cigar": 109, 
        "light": 1175, 
        "diamond": 63, 
        "flash": 100, 
        "cross": 13, 
        "sphere": 316, 
        "other": 324, 
        "formation": 135, 
        "teardrop": 44, 
        "chevron": 36, 
        "unknown": 475, 
        "oval": 221, 
        "changing": 122, 
        "circle": 492, 
        "disk": 225, 
        "egg": 45, 
        "rectangle": 78, 
        "cone": 29
    }, 
    "2010": {
        "cylinder": 35, 
        "fireball": 250, 
        "triangle": 227, 
        "light": 671, 
        "flash": 47, 
        "egg": 9, 
        "cross": 11, 
        "sphere": 192, 
        "diamond": 39, 
        "formation": 71, 
        "teardrop": 32, 
        "chevron": 25, 
        "unknown": 262, 
        "oval": 109, 
        "changing": 86, 
        "circle": 285, 
        "disk": 123, 
        "cigar": 56, 
        "other": 171, 
        "rectangle": 39, 
        "cone": 5
    }
};
var min_year = 1985;
var max_year = 1986;

function httpGet(theUrl)
{
    var xmlHttp = null;

    xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", theUrl, false );
    xmlHttp.send();
    return xmlHttp.responseText;
}
var my_data = httpGet("http://localhost:8983/solr/select?q=*:*&fl=id,title,date_created_s&wt=json&indent=true&rows=10&facet=true&facet.field=science_keywords_s");

my_data = {
    "responseHeader":{
        "status":0,
        "QTime":8,
        "params":{
            "q":"*:*",
            "facet.field":"science_keywords_s",
            "indent":"true",
            "fl":"id,title,date_created_s",
            "rows":"10",
            "wt":"json",
            "facet":"true"}},
    "response":{"numFound":1558,"start":0,"docs":[
        {
            "title":["Project: ARCSS: NSF Arctic System Science"],
            "id":"html-2"},
        {
            "id":"html-6",
            "date_created_s":" 2014-11-25 10:16:11",
            "title":["Arctic Shorebird Demographics Network"]},
        {
            "id":"html-3",
            "date_created_s":" 2013-06-21 20:48:41",
            "title":["Dissolved Fe in soil pore water, 2011"]},
        {
            "title":["ArcticRIMS: Daily Precipitation, From Monthly Station Records And Disaggregation, Aggregated by Administrative Regions"],
            "id":"html-8",
            "date_created_s":" 2009-10-21 00:46:55"},
        {
            "title":["HLY-06-01 Raw Knudsen 320B/R Depth Sounder Data [Grebmeier/LDEO]"],
            "id":"html-4",
            "date_created_s":" 2011-05-16 21:08:45"},
        {
            "id":"html-7",
            "date_created_s":" 2013-11-22 15:36:58",
            "title":["Summit 2010 Ice Core"]},
        {
            "id":"html-9",
            "date_created_s":" 2009-11-18 16:01:04",
            "title":["UVSIMN GUV Barrow 1 Minute Data"]},
        {
            "title":["Sediment trap data of vertical flux of algal pigments, POC and PON"],
            "id":"html-0",
            "date_created_s":" 2012-08-28 04:48:00"},
        {
            "title":["Biomass by Functional Type - Franklin Bluffs MNT Site (Excel) [Walker, D.]"],
            "id":"html-5",
            "date_created_s":" 2011-09-14 05:35:51"},
        {
            "title":["Council Site Characteristics [Beringer, J.]"],
            "id":"html-1",
            "date_created_s":" 2007-11-02 01:29:53"}]
    },
    "facet_counts":{
        "facet_queries":{},
        "facet_fields":{
            "science_keywords_s":[
                " Cryosphere,Snow/Ice,Snow Cover Terrestrial Hydrosphere,Surface Water,Lakes Terrestrial Hydrosphere,Glaciers/Ice Sheets,Glaciers Cryosphere,Snow/Ice,Lake Ice",52,
            " Biosphere,Terrestrial Ecosystems,Alpine/Tundra",41,
            " Cryosphere,Frozen Ground,Periglacial Processes Cryosphere,Frozen Ground,Soil Temperature Paleoclimate,Land Records,Sediments Land Surface,Erosion/Sedimentation,Suspended Solids Cryosphere,Glaciers/Ice Sheets,Glacier Mass Balance/Ice Sheet Mass Balance Paleoclimate,Ocean/Lake Records,Lake Levels Paleoclimate,Ocean/Lake Records,Varve Deposits Land Surface,Land Temperature,Land Surface Temperature Land Surface,Erosion/Sedimentation,Sedimentation Terrestrial Hydrosphere,Glaciers/Ice Sheets,Glacier Mass Balance/Ice Sheet Mass Balance Paleoclimate,Ocean/Lake Records,Sediments Cryosphere,Glaciers/Ice Sheets,Glaciers Land Surface,Erosion/Sedimentation,Degradation Terrestrial Hydrosphere,Glaciers/Ice Sheets,Glaciers Oceans,Ocean Temperature,Water Temperature Land Surface,Erosion/Sedimentation,Entrainment Land Surface,Erosion/Sedimentation,Sediments Land Surface,Erosion/Sedimentation,Sediment Transport Oceans,Marine Sediments,Sediment Transport Oceans,Marine Sediments,Turbidity",24,
            " Human Dimensions,Population,Population Size",23,
            " Cryosphere,Frozen Ground,Active Layer",18,
            " Land Surface,Erosion/Sedimentation,Degradation Cryosphere,Frozen Ground,Periglacial Processes Paleoclimate,Land Records,Sediments Land Surface,Erosion/Sedimentation,Sediment Transport Land Surface,Erosion/Sedimentation,Sediments Land Surface,Erosion/Sedimentation,Entrainment Land Surface,Erosion/Sedimentation,Suspended Solids Paleoclimate,Ocean/Lake Records,Varve Deposits Land Surface,Erosion/Sedimentation,Sedimentation Paleoclimate,Ocean/Lake Records,Sediments",18,
            " Land Surface,Landscape,Landscape Ecology",16,
            " Atmosphere,Atmospheric Radiation,Ultraviolet Radiation",11,
            " Cryosphere,Glaciers/Ice Sheets,Ice Sheets",11,
            " Oceans,Ocean Circulation,Fresh Water Flux",11,
            " Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species",10,
            " Terrestrial Hydrosphere,Surface Water,Discharge/Flow",10,
            " Terrestrial Hydrosphere,Water Quality/Water Chemistry,Conductivity Terrestrial Hydrosphere,Water Quality/Water Chemistry,Water Temperature",10,
            " Biosphere,Aquatic Ecosystems,Plankton,Zooplankton",9,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",9,
            " Biosphere,Aquatic Ecosystems,Lakes",8,
            " Oceans,Ocean Chemistry,Oxygen",8,
            " Atmosphere,Altitude,Tropopause",7,
            " Atmosphere,Clouds,Cloud Properties",7,
            " Biosphere,Aquatic Ecosystems,Wetlands,Peatlands",7,
            " Land Surface,Soils,Soil Moisture/Water Content",7,
            " Agriculture,Soils,Permafrost",6,
            " Biosphere,Ecological Dynamics,Fire Ecology,Fire Dynamics Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",6,
            " Biosphere,Terrestrial Ecosystems,Wetlands,Peatlands",6,
            " Climate Indicators,Atmospheric/Ocean Indicators,Temperature Indices,Common Sense Climate Index",6,
            " Land Surface,Soils,Soil Temperature",6,
            " Land Surface,Surface Radiative Properties,Reflectance",6,
            " Oceans,Ocean Circulation,Water Masses",6,
            " Atmosphere,Atmospheric Temperature,Air Temperature",5,
            " Cryosphere,Frozen Ground,Permafrost",5,
            " Cryosphere,Snow/Ice,Snow Cover Cryosphere,Snow/Ice,Snow Depth Cryosphere,Snow/Ice,Snow/Ice Temperature",5,
            " Oceans,Ocean Circulation,Ocean Mixed Layer",5,
            " Oceans,Ocean Heat Budget,Evaporation",5,
            " Terrestrial Hydrosphere,Surface Water,Water Depth Terrestrial Hydrosphere,Surface Water,Lakes Terrestrial Hydrosphere,Water Quality/Water Chemistry,Water Temperature",5,
            " Atmosphere,Aerosols,Nitrate Particles Atmosphere,Aerosols,Dust/Ash/Smoke Cryosphere,Snow/Ice,Snow/Ice Chemistry Atmosphere,Aerosols,Sulfate Particles Atmosphere,Aerosols,Carbonaceous Aerosols",4,
            " Atmosphere,Clouds,Cloud Microphysics,Cloud Liquid Water/Ice",4,
            " Biosphere,Aquatic Ecosystems,Plankton,Phytoplankton",4,
            " Biosphere,Vegetation,Plant Phenology",4,
            " Biosphere,Vegetation,Vegetation Cover",4,
            " Oceans,Ocean Chemistry,Nitrate",4,
            " Oceans,Ocean Heat Budget,Advection Oceans,Ocean Acoustics,Acoustic Scattering",4,
            " Oceans,Ocean Temperature,Ocean Mixed Layer Oceans,Salinity/Density,Conductivity Oceans,Ocean Temperature,Thermocline Oceans,Salinity/Density,Pycnocline",4,
            " Terrestrial Hydrosphere,Surface Water,Surface Water Chemistry",4,
            " Terrestrial Hydrosphere,Surface Water,Water Depth Terrestrial Hydrosphere,Surface Water,Lakes Terrestrial Hydrosphere,Water Quality/Water Chemistry,Conductivity Terrestrial Hydrosphere,Water Quality/Water Chemistry,Water Temperature",4,
            " Terrestrial Hydrosphere,Water Quality/Water Chemistry,Phosphorous Compounds Terrestrial Hydrosphere,Water Quality/Water Chemistry,Nutrients Terrestrial Hydrosphere,Surface Water,Rivers/Streams",4,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",3,
            " Biological Classification,Animals/Invertebrates",3,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Nutrient Cycling",3,
            " Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Ecosystem Functions,Primary Production",3,
            " Biosphere,Vegetation,Vegetation Species",3,
            " Climate Indicators,Atmospheric/Ocean Indicators Atmosphere,Atmospheric Chemistry Biosphere,Vegetation,Vegetation Species Land Surface,Landscape,Landscape Ecology Biosphere,Vegetation,Vegetation Cover",3,
            " Cryosphere,Glaciers/Ice Sheets,Glaciers",3,
            " Cryosphere,Sea Ice,Snow Depth Cryosphere,Snow/Ice,Snow Cover Cryosphere,Snow/Ice,Snow Melt Cryosphere,Snow/Ice,Snow Depth Atmosphere,Atmospheric Winds,Convergence/Divergence Cryosphere,Snow/Ice,Snow/Ice Temperature Atmosphere,Atmospheric Water Vapor,Humidity",3,
            " Cryosphere,Snow/Ice,Snow Cover Cryosphere,Snow/Ice,Snow Depth",3,
            " Human Dimensions,Social Behavior",3,
            " Oceans,Ocean Circulation,Ocean Currents",3,
            " Solid Earth,Geochemistry,Geochemical Properties,Isotopes Cryosphere,Glaciers/Ice Sheets,Glaciers",3,
            " Terrestrial Hydrosphere,Surface Water,Water Depth",3,
            " Agriculture,Soils,Carbon",2,
            " Agriculture,Soils,Microflora Agriculture,Soils,Soil Chemistry Agriculture,Soils,Soil Gas/Air Agriculture,Soils,Permafrost Biosphere,Ecological Dynamics,Ecosystem Functions,Biomass Dynamics Agriculture,Soils,Soil Ph Agriculture,Soils,Carbon Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",2,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds",2,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",2,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",2,
            " Atmosphere,Atmospheric Pressure,Gravity Wave Atmosphere,Atmospheric Radiation,Airglow",2,
            " Biosphere",2,
            " Biosphere,Aquatic Ecosystems,Plankton",2,
            " Biosphere,Ecological Dynamics",2,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Primary Production Biosphere,Vegetation,Nutrients Biosphere,Ecological Dynamics,Ecosystem Functions,Biomass Dynamics",2,
            " Biosphere,Ecological Dynamics,Fire Ecology,Fire Dynamics Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Community Dynamics,Species Recruitment Biosphere,Ecological Dynamics,Community Dynamics,Plant Succession Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",2,
            " Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",2,
            " Biosphere,Vegetation,Plant Characteristics",2,
            " Biosphere,Vegetation,Vegetation Index",2,
            " Climate Indicators,Paleoclimate Indicators,Land Records,Boreholes",2,
            " Cryosphere,Frozen Ground,Permafrost Land Surface,Frozen Ground,Permafrost",2,
            " Cryosphere,Glaciers/Ice Sheets,Firn",2,
            " Cryosphere,Glaciers/Ice Sheets,Glacier Topography/Ice Sheet Topography Cryosphere,Glaciers/Ice Sheets,Glacier Thickness/Ice Sheet Thickness Cryosphere,Glaciers/Ice Sheets,Glaciers",2,
            " Cryosphere,Sea Ice,Sea Ice Motion",2,
            " Cryosphere,Sea Ice,Snow Depth Cryosphere,Snow/Ice,Snow Cover Cryosphere,Snow/Ice,Snow Density Cryosphere,Snow/Ice,Snow Melt Cryosphere,Snow/Ice,Snow Depth Atmosphere,Atmospheric Winds,Convergence/Divergence Cryosphere,Snow/Ice,Snow/Ice Temperature Atmosphere,Atmospheric Water Vapor,Humidity",2,
            " Cryosphere,Snow/Ice,Snow Cover",2,
            " Cryosphere,Snow/Ice,Snow Cover Cryosphere,Snow/Ice,Snow Depth Atmosphere,Atmospheric Winds,Convergence/Divergence Cryosphere,Snow/Ice,Snow/Ice Temperature Atmosphere,Atmospheric Water Vapor,Humidity Cryosphere,Snow/Ice,Lake Ice",2,
            " Cryosphere,Snow/Ice,Snow Depth",2,
            " Cryosphere,Snow/Ice,Snow Water Equivalent",2,
            " Cryosphere,Snow/Ice,Snow/Ice Chemistry",2,
            " Land Surface,Landscape,Landscape Patterns",2,
            " Land Surface,Soils,Organic Matter Oceans,Coastal Processes,Estuaries Biosphere,Vegetation,Indigenous Vegetation Oceans,Ocean Chemistry,Carbon Paleoclimate,Ocean/Lake Records,Sediments",2,
            " Land Surface,Soils,Soil Moisture/Water Content Atmosphere,Atmospheric Temperature,Air Temperature Cryosphere,Frozen Ground,Soil Temperature Land Surface,Soils,Soil Temperature Atmosphere,Atmospheric Water Vapor,Humidity Biosphere,Terrestrial Ecosystems,Alpine/Tundra",2,
            " Oceans,Marine Sediments,Sediment Chemistry",2,
            " Oceans,Ocean Acoustics,Ambient Noise Biological Classification,Animals/Vertebrates,Mammals,Carnivores,Seals/Sea Lions/Walruses Biological Classification,Animals/Vertebrates,Mammals,Cetaceans",2,
            " Oceans,Ocean Chemistry,Marine Geochemistry Climate Indicators,Atmospheric/Ocean Indicators,Fresh Water River Discharge Oceans,Ocean Circulation,Fresh Water Flux Terrestrial Hydrosphere,Surface Water,Rivers/Streams",2,
            " Oceans,Ocean Chemistry,Organic Matter Oceans,Sea Ice,Ice Types Biosphere,Aquatic Ecosystems,Marine Habitat",2,
            " Oceans,Ocean Chemistry,Stable Isotopes",2,
            " Oceans,Ocean Circulation,Water Masses Oceans,Ocean Temperature,Water Temperature Oceans,Salinity/Density,Salinity",2,
            " Oceans,Ocean Optics,Gelbstoff Oceans,Salinity/Density,Conductivity Oceans,Salinity/Density,Density Oceans,Ocean Temperature,Water Temperature Oceans,Ocean Optics,Scattering Oceans,Salinity/Density,Salinity Oceans,Ocean Optics,Fluorescence",2,
            " Oceans,Ocean Pressure,Water Pressure",2,
            " Oceans,Ocean Temperature Oceans,Salinity/Density,Salinity",2,
            " Oceans,Salinity/Density,Density Oceans,Ocean Temperature,Water Temperature Oceans,Ocean Chemistry,Nutrients Oceans,Ocean Chemistry,Pigments,Chlorophyll Oceans,Salinity/Density,Salinity",2,
            " Oceans,Salinity/Density,Salinity",2,
            " Oceans,Sea Ice,Ice Depth/Thickness",2,
            " Oceans,Sea Ice,Ice Depth/Thickness Oceans,Ocean Temperature,Water Temperature Oceans,Ocean Circulation,Fresh Water Flux",2,
            " Oceans,Sea Ice,Ice Temperature",2]},
        "facet_dates":{},
        "facet_ranges":{},
        "facet_intervals":{}
    }
};
console.log(my_data.response.docs[0].id);
min = 10000;
max = 0;
for (i = 0; i < my_data.response.docs.length; i++) {
    if (my_data.response.docs[i].date_created_s !== undefined) {
        min = min > my_data.response.docs[i].date_created_s.trim().split("-")[0] ? my_data.response.docs[i].date_created_s.trim().split("-")[0] : min;
        max = max < my_data.response.docs[i].date_created_s.trim().split("-")[0] ? my_data.response.docs[i].date_created_s.trim().split("-")[0] : max;
    }
}
console.log("min value is: " + min);
console.log("max value is: " + max);

var min_year_data = httpGet("http://localhost:8983/solr/select?q=date_created_s:%20*" + min + "*&wt=json&indent=true&rows=10&facet=true&facet.field=science_keywords_s");
var max_year_data = httpGet("http://localhost:8983/solr/select?q=date_created_s:%20*" + max + "*&wt=json&indent=true&rows=10&facet=true&facet.field=science_keywords_s");


min_year_data = {
    "responseHeader":{
        "status":0,
        "QTime":8,
        "params":{
            "q":"date_created_s: *2007*",
            "facet.field":"science_keywords_s",
            "indent":"true",
            "rows":["0",
            "10"],
            "wt":"json",
            "facet":"true"}},
    "response":{"numFound":277,"start":0,"docs":[]
    },
    "facet_counts":{
        "facet_queries":{},
        "facet_fields":{
            "science_keywords_s":[
                " Agriculture,Soils,Carbon",0,
            " Agriculture,Soils,Microflora Agriculture,Soils,Soil Chemistry Agriculture,Soils,Soil Gas/Air Agriculture,Soils,Permafrost Biosphere,Ecological Dynamics,Ecosystem Functions,Biomass Dynamics Agriculture,Soils,Soil Ph Agriculture,Soils,Carbon Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Agriculture,Soils,Permafrost",0,
            " Atmosphere,Aerosols,Nitrate Particles Atmosphere,Aerosols,Dust/Ash/Smoke Cryosphere,Snow/Ice,Snow/Ice Chemistry Atmosphere,Aerosols,Sulfate Particles",0,
            " Atmosphere,Aerosols,Nitrate Particles Atmosphere,Aerosols,Dust/Ash/Smoke Cryosphere,Snow/Ice,Snow/Ice Chemistry Atmosphere,Aerosols,Sulfate Particles Atmosphere,Aerosols,Carbonaceous Aerosols",0,
            " Atmosphere,Aerosols,Particulate Matter Cryosphere,Glaciers/Ice Sheets,Firn Atmosphere,Air Quality,Emissions Atmosphere,Precipitation,Snow Atmosphere,Aerosols,Dust/Ash/Smoke Paleoclimate,Ice Core Records,Isotopes Atmosphere,Air Quality,Lead Paleoclimate,Ice Core Records,Particulate Matter Cryosphere,Snow/Ice,Snow/Ice Chemistry Atmosphere,Atmospheric Chemistry,Trace Elements/Trace Metals Atmosphere,Air Quality,Particulates Cryosphere,Glaciers/Ice Sheets,Glaciers",0,
            " Atmosphere,Air Quality,Nitrogen Oxides",0,
            " Atmosphere,Altitude,Barometric Altitude",0,
            " Atmosphere,Altitude,Barometric Altitude Atmosphere,Atmospheric Water Vapor,Water Vapor Profiles Atmosphere,Atmospheric Temperature,Temperature Profiles",0,
            " Atmosphere,Altitude,Tropopause",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Methane",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction Atmosphere,Atmospheric Chemistry,Halocarbons And Halogens,Bromine Monoxide",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Biosphere,Ecological Dynamics,Ecosystem Functions,Decomposition Biosphere,Vegetation,Nitrogen Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Biosphere,Ecological Dynamics,Ecosystem Functions,Respiration Rate Land Surface,Soils,Soil Gas/Air Land Surface,Soils,Soil Respiration Land Surface,Frozen Ground,Soil Temperature",0,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone",0,
            " Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species",0,
            " Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Chemistry,Nitrogen Compounds,Nitrogen Oxides",0,
            " Atmosphere,Atmospheric Pressure,Atmospheric Pressure Measurements",0,
            " Atmosphere,Atmospheric Pressure,Gravity Wave",0,
            " Atmosphere,Atmospheric Pressure,Gravity Wave Atmosphere,Atmospheric Radiation,Airglow",0,
            " Atmosphere,Atmospheric Pressure,Planetary Boundary Layer Height Atmosphere,Altitude,Planetary Boundary Layer Height",0,
            " Atmosphere,Atmospheric Pressure,Pressure Tendency Atmosphere,Atmospheric Temperature,Air Temperature Atmosphere,Atmospheric Temperature,Surface Air Temperature Cryosphere,Frozen Ground,Soil Temperature Land Surface,Soils,Soil Temperature Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds Land Surface,Frozen Ground,Soil Temperature",0,
            " Atmosphere,Atmospheric Pressure,Surface Pressure",0,
            " Atmosphere,Atmospheric Radiation,Atmospheric Emitted Radiation",0,
            " Atmosphere,Atmospheric Radiation,Optical Depth/Thickness",0,
            " Atmosphere,Atmospheric Radiation,Reflectance Atmosphere,Atmospheric Temperature,Surface Air Temperature Oceans,Sea Ice,Sea Ice Concentration Biosphere,Terrestrial Ecosystems,Wetlands,Marine Land Surface,Land Temperature,Land Surface Temperature Biosphere,Terrestrial Ecosystems,Alpine/Tundra Cryosphere,Sea Ice,Sea Ice Concentration",0,
            " Atmosphere,Atmospheric Radiation,Reflectance Atmosphere,Atmospheric Temperature,Surface Air Temperature Oceans,Sea Ice,Sea Ice Concentration Land Surface,Land Temperature,Land Surface Temperature Biosphere,Terrestrial Ecosystems,Alpine/Tundra Cryosphere,Sea Ice,Sea Ice Concentration",0,
            " Atmosphere,Atmospheric Radiation,Ultraviolet Radiation",0,
            " Atmosphere,Atmospheric Radiation,Ultraviolet Radiation Atmosphere,Atmospheric Radiation,Optical Depth/Thickness",0,
            " Atmosphere,Atmospheric Temperature,Air Temperature",0,
            " Atmosphere,Atmospheric Temperature,Air Temperature Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Precipitation,Rain Land Surface,Land Temperature,Land Heat Capacity Biosphere,Terrestrial Ecosystems,Alpine/Tundra Land Surface,Frozen Ground,Soil Temperature",0,
            " Atmosphere,Atmospheric Temperature,Potential Temperature",0,
            " Atmosphere,Atmospheric Temperature,Static Temperature Atmosphere,Atmospheric Temperature,Air Temperature Atmosphere,Atmospheric Radiation,Incoming Solar Radiation Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Precipitation,Rain Land Surface,Frozen Ground,Soil Temperature",0,
            " Atmosphere,Atmospheric Temperature,Temperature Profiles",0,
            " Atmosphere,Atmospheric Temperature,Temperature Profiles Atmosphere,Clouds,Cloud Microphysics,Cloud Liquid Water/Ice Atmosphere,Atmospheric Radiation,Atmospheric Emitted Radiation Atmosphere,Atmospheric Water Vapor,Precipitable Water",0,
            " Atmosphere,Atmospheric Water Vapor,Precipitable Water",0,
            " Atmosphere,Clouds,Cloud Microphysics,Cloud Liquid Water/Ice",0,
            " Atmosphere,Clouds,Cloud Microphysics,Cloud Liquid Water/Ice Atmosphere,Atmospheric Radiation,Radiative Forcing Atmosphere,Atmospheric Radiation,Longwave Radiation Atmosphere,Atmospheric Radiation,Emissivity Atmosphere,Clouds,Cloud Radiative Transfer,Cloud Emissivity Atmosphere,Atmospheric Radiation,Optical Depth/Thickness Atmosphere,Atmospheric Radiation,Atmospheric Emitted Radiation Atmosphere,Atmospheric Radiation,Radiative Flux Atmosphere,Clouds,Cloud Microphysics,Cloud Optical Depth/Thickness",0,
            " Atmosphere,Clouds,Cloud Properties",0,
            " Atmosphere,Clouds,Cloud Properties,Cloud Base Height Atmosphere,Aerosols,Aerosol Backscatter Atmosphere,Clouds,Cloud Properties,Cloud Height Atmosphere,Clouds,Cloud Properties",0,
            " Atmosphere,Clouds,Cloud Properties,Cloud Base Height Atmosphere,Clouds,Cloud Properties,Cloud Height Atmosphere,Clouds,Cloud Properties Atmosphere,Clouds,Cloud Properties,Cloud Ceiling",0,
            " Atmosphere,Clouds,Cloud Properties,Cloud Base Height Atmosphere,Clouds,Cloud Properties,Cloud Vertical Distribution Atmosphere,Clouds,Cloud Properties,Cloud Height Atmosphere,Clouds,Cloud Properties",0,
            " Atmosphere,Clouds,Cloud Properties,Cloud Vertical Distribution",0,
            " Atmosphere,Clouds,Cloud Properties,Cloud Vertical Distribution Atmosphere,Aerosols,Aerosol Backscatter Atmosphere,Clouds,Cloud Properties,Cloud Height",0,
            " Atmosphere,Precipitation,Snow Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Precipitation,Rain Atmosphere,Precipitation,Precipitation Amount",0,
            " Atmosphere,Precipitation,Snow Atmosphere,Precipitation,Precipitation Rate Atmosphere,Precipitation,Rain Atmosphere,Precipitation,Precipitation Amount",0,
            " Biological Classification,Animals/Invertebrates",0,
            " Biological Classification,Animals/Invertebrates Oceans Biosphere,Aquatic Ecosystems,Plankton",0,
            " Biological Classification,Animals/Vertebrates,Fish,Ray-Finned Fishes,Cods/Haddocks",0,
            " Biological Classification,Animals/Vertebrates,Mammals,Carnivores,Seals/Sea Lions/Walruses",0,
            " Biological Classification,Bacteria/Archaea,Cyanobacteria (Blue-Green Algae) Biological Classification,Bacteria/Archaea",0,
            " Biological Classification,Plants,Gymnosperms,Conifers",0,
            " Biological Classification,Plants,Microalgae",0,
            " Biological Classification,Protists,Plankton Oceans,Aquatic Sciences",0,
            " Biosphere",0,
            " Biosphere,Aquatic Ecosystems,Lakes",0,
            " Biosphere,Aquatic Ecosystems,Pelagic Habitat",0,
            " Biosphere,Aquatic Ecosystems,Plankton",0,
            " Biosphere,Aquatic Ecosystems,Plankton,Phytoplankton",0,
            " Biosphere,Aquatic Ecosystems,Plankton,Phytoplankton Oceans,Salinity/Density,Conductivity Oceans,Ocean Optics,Photosynthetically Active Radiation Oceans,Ocean Temperature,Water Temperature Oceans,Salinity/Density,Salinity Oceans,Ocean Optics,Fluorescence",0,
            " Biosphere,Aquatic Ecosystems,Plankton,Phytoplankton Oceans,Salinity/Density,Conductivity Oceans,Salinity/Density,Density Oceans,Ocean Temperature,Water Temperature Oceans,Ocean Chemistry,Nutrients Biosphere,Aquatic Ecosystems,Plankton Oceans,Salinity/Density,Salinity Biosphere,Aquatic Ecosystems,Plankton,Zooplankton",0,
            " Biosphere,Aquatic Ecosystems,Plankton,Phytoplankton Oceans,Salinity/Density,Density Biosphere,Aquatic Ecosystems,Pelagic Habitat Oceans,Ocean Temperature,Water Temperature Oceans,Ocean Chemistry,Nutrients Biosphere,Aquatic Ecosystems,Plankton Oceans,Salinity/Density,Salinity Biosphere,Aquatic Ecosystems,Marine Habitat Biosphere,Aquatic Ecosystems,Plankton,Zooplankton",0,
            " Biosphere,Aquatic Ecosystems,Plankton,Zooplankton",0,
            " Biosphere,Aquatic Ecosystems,Wetlands,Peatlands",0,
            " Biosphere,Ecological Dynamics",0,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Nutrient Cycling",0,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Primary Production Biosphere,Vegetation,Nutrients Biosphere,Ecological Dynamics,Ecosystem Functions,Biomass Dynamics",0,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Primary Production Biosphere,Vegetation,Tree Rings",0,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Respiration Rate",0,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Respiration Rate Biosphere,Vegetation,Photosynthetically Active Radiation Terrestrial Hydrosphere,Ground Water,Ground Water Discharge/Flow",0,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Respiration Rate Biosphere,Vegetation,Vegetation Index Biosphere,Ecological Dynamics,Ecosystem Functions,Photosynthesis Biosphere,Terrestrial Ecosystems,Wetlands,Peatlands Land Surface,Frozen Ground,Soil Temperature",0,
            " Biosphere,Ecological Dynamics,Fire Ecology,Fire Dynamics Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Community Dynamics,Species Recruitment Biosphere,Ecological Dynamics,Community Dynamics,Plant Succession Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Biosphere,Ecological Dynamics,Fire Ecology,Fire Dynamics Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Biosphere,Ecological Dynamics,Fire Ecology,Fire Dynamics Biosphere,Terrestrial Ecosystems,Forests Land Surface,Soils,Permafrost Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Biosphere,Ecological Dynamics,Fire Ecology,Fire Dynamics Biosphere,Terrestrial Ecosystems,Forests Land Surface,Soils,Soil Temperature Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Biosphere,Ecological Dynamics,Species/Population Interactions,Endangered Species",0,
            " Biosphere,Ecological Dynamics,Species/Population Interactions,Grazing Dynamics/Plant Herbivory Biosphere,Terrestrial Ecosystems,Forests Human Dimensions,Infrastructure,Cultural Features Human Dimensions,Environmental Governance/Management,Land Management,Land Tenure Human Dimensions,Environmental Impacts,Conservation Human Dimensions,Boundaries,Political Divisions Biosphere,Terrestrial Ecosystems,Alpine/Tundra Land Surface,Frozen Ground,Permafrost Human Dimensions,Economic Resources,Agriculture Production Land Surface,Landscape,Landscape Management Cryosphere,Frozen Ground,Permafrost Cryosphere,Frozen Ground,Active Layer Biosphere,Ecological Dynamics,Species/Population Interactions,Species Life History Cryosphere,Frozen Ground,Seasonally Frozen Ground Cryosphere,Snow/Ice,Permafrost Land Surface,Frozen Ground,Seasonally Frozen Ground Human Dimensions,Boundaries,Administrative Divisions Human Dimensions,Environmental Governance/Management,Land Management",0,
            " Biosphere,Ecological Dynamics,Species/Population Interactions,Indigenous/Native Species Cryosphere,Sea Ice,Polynyas Atmosphere,Atmospheric Winds,Wind Chill Atmosphere,Atmospheric Temperature,Air Temperature Cryosphere,Sea Ice,Salinity Atmosphere,Precipitation,Rain Atmosphere,Atmospheric Winds,Surface Winds Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Ecological Dynamics,Community Dynamics,Biodiversity Functions Cryosphere,Sea Ice,Leads Cryosphere,Sea Ice,Ice Floes Cryosphere,Sea Ice,Ice Extent Cryosphere,Sea Ice,Ice Edges",0,
            " Biosphere,Terrestrial Ecosystems",0,
            " Biosphere,Terrestrial Ecosystems,Alpine/Tundra",0,
            " Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Biosphere,Terrestrial Ecosystems,Deserts",0,
            " Biosphere,Terrestrial Ecosystems,Forests",0,
            " Biosphere,Terrestrial Ecosystems,Forests Atmosphere,Atmospheric Water Vapor,Evapotranspiration",0,
            " Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Ecosystem Functions,Nutrient Cycling Biosphere,Ecological Dynamics,Ecosystem Functions,Respiration Rate Biosphere,Ecological Dynamics,Ecosystem Functions,Photosynthesis",0,
            " Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Ecosystem Functions,Primary Production",0,
            " Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Ecosystem Functions,Primary Production Biosphere,Vegetation,Tree Rings",0,
            " Biosphere,Terrestrial Ecosystems,Forests Biosphere,Vegetation,Dominant Species Human Dimensions,Environmental Impacts,Conservation Biosphere,Terrestrial Ecosystems,Shrubland/Scrub Biosphere,Vegetation,Biomass Biosphere,Ecological Dynamics,Community Dynamics,Plant Succession Biosphere,Terrestrial Ecosystems,Grasslands Biosphere,Vegetation,Vegetation Cover Biosphere,Ecological Dynamics,Community Dynamics,Biodiversity Functions",0,
            " Biosphere,Terrestrial Ecosystems,Wetlands,Peatlands",0,
            " Biosphere,Vegetation,Chlorophyll Atmosphere,Atmospheric Radiation,Solar Radiation",0,
            " Biosphere,Vegetation,Dominant Species Biosphere,Vegetation,Biomass Biosphere,Vegetation,Carbon Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",0,
            " Biosphere,Vegetation,Evergreen Vegetation Biosphere,Ecological Dynamics,Community Dynamics,Invasive Species Biosphere,Vegetation,Plant Characteristics Biosphere,Vegetation,Tree Rings",0,
            " Biosphere,Vegetation,Evergreen Vegetation Biosphere,Terrestrial Ecosystems,Forests Biosphere,Terrestrial Ecosystems,Montane Habitats Biosphere,Vegetation,Tree Rings",0,
            " Biosphere,Vegetation,Evergreen Vegetation Biosphere,Terrestrial Ecosystems,Forests Paleoclimate,Paleoclimate Reconstructions,Drought/Precipitation Reconstruction Paleoclimate,Land Records,Tree Rings Paleoclimate,Land Records,Macrofossils Paleoclimate,Land Records,Isotopes Biosphere,Vegetation,Carbon Biosphere,Vegetation,Tree Rings",0]},
        "facet_dates":{},
        "facet_ranges":{},
        "facet_intervals":{}
    }
};
max_year_data = {
    "responseHeader":{
        "status":0,
        "QTime":2,
        "params":{
            "q":"date_created_s: *2014*",
            "facet.field":"science_keywords_s",
            "indent":"true",
            "fl":"id",
            "rows":"0",
            "wt":"json",
            "facet":"true"}},
    "response":{"numFound":146,"start":0,"docs":[]
    },
    "facet_counts":{
        "facet_queries":{},
        "facet_fields":{
            "science_keywords_s":[
                " Biosphere,Aquatic Ecosystems,Plankton,Phytoplankton",4,
            " Biosphere,Aquatic Ecosystems,Plankton,Zooplankton",4,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",4,
            " Biosphere,Terrestrial Ecosystems,Alpine/Tundra",4,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",3,
            " Biological Classification,Animals/Invertebrates",3,
            " Climate Indicators,Atmospheric/Ocean Indicators Atmosphere,Atmospheric Chemistry Biosphere,Vegetation,Vegetation Species Land Surface,Landscape,Landscape Ecology Biosphere,Vegetation,Vegetation Cover",3,
            " Solid Earth,Geochemistry,Geochemical Properties,Isotopes Cryosphere,Glaciers/Ice Sheets,Glaciers",3,
            " Terrestrial Hydrosphere,Surface Water,Water Depth Terrestrial Hydrosphere,Surface Water,Lakes Terrestrial Hydrosphere,Water Quality/Water Chemistry,Conductivity Terrestrial Hydrosphere,Water Quality/Water Chemistry,Water Temperature",3,
            " Terrestrial Hydrosphere,Surface Water,Water Depth Terrestrial Hydrosphere,Surface Water,Lakes Terrestrial Hydrosphere,Water Quality/Water Chemistry,Water Temperature",3,
            " Agriculture,Soils,Carbon",2,
            " Agriculture,Soils,Microflora Agriculture,Soils,Soil Chemistry Agriculture,Soils,Soil Gas/Air Agriculture,Soils,Permafrost Biosphere,Ecological Dynamics,Ecosystem Functions,Biomass Dynamics Agriculture,Soils,Soil Ph Agriculture,Soils,Carbon Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",2,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds",2,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Water Vapor,Humidity Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",2,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Chemistry,Oxygen Compounds,Ozone Atmosphere,Atmospheric Pressure,Surface Pressure Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction",2,
            " Atmosphere,Atmospheric Pressure,Gravity Wave Atmosphere,Atmospheric Radiation,Airglow",2,
            " Biosphere",2,
            " Biosphere,Aquatic Ecosystems,Plankton",2,
            " Biosphere,Ecological Dynamics",2,
            " Climate Indicators,Paleoclimate Indicators,Land Records,Boreholes",2,
            " Cryosphere,Snow/Ice,Snow/Ice Chemistry",2,
            " Land Surface,Landscape,Landscape Ecology",2,
            " Oceans,Ocean Acoustics,Ambient Noise Biological Classification,Animals/Vertebrates,Mammals,Carnivores,Seals/Sea Lions/Walruses Biological Classification,Animals/Vertebrates,Mammals,Cetaceans",2,
            " Oceans,Ocean Chemistry,Organic Matter Oceans,Sea Ice,Ice Types Biosphere,Aquatic Ecosystems,Marine Habitat",2,
            " Oceans,Ocean Chemistry,Stable Isotopes",2,
            " Oceans,Ocean Heat Budget,Advection Oceans,Ocean Acoustics,Acoustic Scattering",2,
            " Oceans,Ocean Temperature Oceans,Salinity/Density,Salinity",2,
            " Terrestrial Hydrosphere,Surface Water,Lakes Atmosphere",2,
            " Atmosphere,Aerosols,Nitrate Particles Atmosphere,Aerosols,Dust/Ash/Smoke Cryosphere,Snow/Ice,Snow/Ice Chemistry Atmosphere,Aerosols,Sulfate Particles",1,
            " Atmosphere,Aerosols,Nitrate Particles Atmosphere,Aerosols,Dust/Ash/Smoke Cryosphere,Snow/Ice,Snow/Ice Chemistry Atmosphere,Aerosols,Sulfate Particles Atmosphere,Aerosols,Carbonaceous Aerosols",1,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Methane",1,
            " Atmosphere,Atmospheric Chemistry,Carbon And Hydrocarbon Compounds,Carbon Dioxide Biosphere,Ecological Dynamics,Ecosystem Functions,Respiration Rate Land Surface,Soils,Soil Gas/Air Land Surface,Soils,Soil Respiration Land Surface,Frozen Ground,Soil Temperature",1,
            " Atmosphere,Atmospheric Chemistry,Trace Gases/Trace Species Atmosphere,Atmospheric Chemistry,Nitrogen Compounds,Nitrogen Oxides",1,
            " Atmosphere,Precipitation,Snow Atmosphere,Atmospheric Temperature,Surface Air Temperature Atmosphere,Precipitation,Rain Atmosphere,Precipitation,Precipitation Amount",1,
            " Biological Classification,Animals/Invertebrates Oceans Biosphere,Aquatic Ecosystems,Plankton",1,
            " Biological Classification,Animals/Vertebrates,Fish,Ray-Finned Fishes,Cods/Haddocks",1,
            " Biological Classification,Animals/Vertebrates,Mammals,Carnivores,Seals/Sea Lions/Walruses",1,
            " Biological Classification,Bacteria/Archaea,Cyanobacteria (Blue-Green Algae) Biological Classification,Bacteria/Archaea",1,
            " Biological Classification,Plants,Gymnosperms,Conifers",1,
            " Biological Classification,Plants,Microalgae",1,
            " Biological Classification,Protists,Plankton Oceans,Aquatic Sciences",1,
            " Biosphere,Aquatic Ecosystems,Lakes",1,
            " Biosphere,Aquatic Ecosystems,Pelagic Habitat",1,
            " Biosphere,Ecological Dynamics,Ecosystem Functions,Nutrient Cycling",1,
            " Biosphere,Ecological Dynamics,Fire Ecology,Fire Dynamics Biosphere,Terrestrial Ecosystems,Forests Biosphere,Ecological Dynamics,Community Dynamics,Species Recruitment Biosphere,Ecological Dynamics,Community Dynamics,Plant Succession Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",1,
            " Biosphere,Terrestrial Ecosystems",1,
            " Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Ecological Dynamics,Ecosystem Functions,Biogeochemical Cycles",1,
            " Biosphere,Terrestrial Ecosystems,Deserts",1,
            " Biosphere,Vegetation,Vegetation Species Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Vegetation,Vegetation Cover",1,
            " Climate Indicators",1,
            " Climate Indicators,Cryospheric Indicators,Glacial Measurements,Glacier Mass Balance/Ice Sheet Mass Balance Cryosphere,Glaciers/Ice Sheets,Glacier Mass Balance/Ice Sheet Mass Balance Terrestrial Hydrosphere,Glaciers/Ice Sheets,Glacier Mass Balance/Ice Sheet Mass Balance",1,
            " Climate Indicators,Cryospheric Indicators,Snow Cover Land Surface,Soils,Organic Matter Land Surface,Soils Climate Indicators,Cryospheric Indicators,Snow Melt Land Surface,Soils,Phosphorus Land Surface,Soils,Soil Chemistry Land Surface,Frozen Ground,Seasonally Frozen Ground Land Surface,Soils,Nitrogen Land Surface,Soils,Carbon",1,
            " Climate Indicators,Paleoclimate Indicators,Ice Core Records",1,
            " Climate Indicators,Paleoclimate Indicators,Ocean/Lake Records,Sediments Oceans,Ocean Chemistry,Organic Carbon Oceans,Marine Sediments,Biogenic Sediments Oceans,Marine Sediments,Sedimentation Oceans,Marine Sediments,Sediment Composition Climate Indicators,Paleoclimate Indicators,Ocean/Lake Records,Isotopes",1,
            " Climate Indicators,Terrestrial Hydrosphere Indicators,Permafrost Melt Biosphere,Terrestrial Ecosystems Terrestrial Hydrosphere,Surface Water,Surface Water Chemistry Land Surface,Soils,Permafrost",1,
            " Cryosphere Climate Indicators,Paleoclimate Indicators,Ice Core Records Climate Indicators,Cryospheric Indicators,Glacial Measurements",1,
            " Cryosphere,Frozen Ground,Active Layer Land Surface,Soils,Soil Temperature Biosphere,Terrestrial Ecosystems,Shrubland/Scrub Land Surface,Landscape,Landscape Patterns Biological Classification,Plants,Angiosperms (Flowering Plants),Dicots Land Surface,Frozen Ground,Active Layer Biosphere,Ecological Dynamics,Community Dynamics,Plant Succession Biosphere,Terrestrial Ecosystems,Alpine/Tundra Climate Indicators,Land Surface/Agriculture Indicators,Soil Temperature",1,
            " Cryosphere,Frozen Ground,Permafrost",1,
            " Cryosphere,Glaciers/Ice Sheets,Ablation Zones/Accumulation Zones",1,
            " Cryosphere,Glaciers/Ice Sheets,Firn",1,
            " Cryosphere,Glaciers/Ice Sheets,Firn Cryosphere,Glaciers/Ice Sheets",1,
            " Cryosphere,Glaciers/Ice Sheets,Ice Sheets",1,
            " Cryosphere,Glaciers/Ice Sheets,Ice Sheets Terrestrial Hydrosphere,Snow/Ice,River Ice Biological Classification,Bacteria/Archaea",1,
            " Cryosphere,Sea Ice,Ice Temperature Oceans,Ocean Chemistry,Organic Carbon Biological Classification,Bacteria/Archaea Biosphere,Aquatic Ecosystems,Coastal Habitat Oceans,Ocean Chemistry,Ammonia Oceans,Sea Ice,Salinity",1,
            " Cryosphere,Snow/Ice,River Ice Biological Classification,Bacteria/Archaea Terrestrial Hydrosphere,Surface Water,Discharge/Flow",1,
            " Cryosphere,Snow/Ice,Snow Water Equivalent",1,
            " Land Surface,Soils,Organic Matter Land Surface,Soils,Soil Horizons/Profile Cryosphere,Frozen Ground,Active Layer Biosphere,Terrestrial Ecosystems,Shrubland/Scrub Land Surface,Landscape,Landscape Patterns Biological Classification,Plants,Angiosperms (Flowering Plants),Dicots Biosphere,Vegetation,Plant Characteristics Land Surface,Frozen Ground,Periglacial Processes Land Surface,Frozen Ground,Active Layer Biosphere,Ecological Dynamics,Community Dynamics,Plant Succession Biosphere,Terrestrial Ecosystems,Alpine/Tundra Biosphere,Ecological Dynamics,Community Dynamics,Community Structure",1,
            " Land Surface,Soils,Soil Gas/Air Land Surface,Soils,Carbon Land Surface,Frozen Ground,Soil Temperature",1,
            " Land Surface,Soils,Soil Moisture/Water Content Cryosphere,Frozen Ground,Active Layer Biosphere,Ecological Dynamics,Fire Ecology Land Surface,Frozen Ground,Active Layer Land Surface,Soils,Electrical Conductivity Land Surface,Frozen Ground,Soil Temperature",1,
            " Land Surface,Soils,Soil Respiration Biosphere,Terrestrial Ecosystems,Alpine/Tundra",1,
            " Oceans",1,
            " Oceans Biological Classification,Protists,Plankton Biosphere,Ecological Dynamics,Community Dynamics,Community Structure",1,
            " Oceans Biosphere,Aquatic Ecosystems,Plankton",1,
            " Oceans Biosphere,Aquatic Ecosystems,Plankton,Zooplankton",1,
            " Oceans,Coastal Processes Oceans,Ocean Temperature Oceans,Salinity/Density,Conductivity Oceans,Ocean Pressure Oceans,Ocean Optics",1,
            " Oceans,Coastal Processes,Estuaries Oceans,Ocean Chemistry,Biogeochemical Cycles Biosphere,Aquatic Ecosystems,Estuarine Habitat",1,
            " Oceans,Coastal Processes,Sediment Transport",1,
            " Oceans,Marine Environment Monitoring Oceans,Ocean Chemistry,Ph Oceans,Ocean Chemistry,Carbon Dioxide Oceans,Ocean Chemistry,Alkalinity",1,
            " Oceans,Ocean Chemistry Oceans,Ocean Chemistry,Ph Oceans,Ocean Chemistry,Carbonate Oceans,Ocean Chemistry,Carbon",1,
            " Oceans,Ocean Chemistry,Carbon Dioxide",1,
            " Oceans,Ocean Chemistry,Organic Matter Biosphere,Aquatic Ecosystems,Marine Habitat Oceans,Sea Ice,Ice Types",1,
            " Oceans,Ocean Chemistry,Ph Oceans,Ocean Chemistry,Carbonate Oceans,Ocean Chemistry,Carbon",1,
            " Oceans,Ocean Circulation Oceans,Ocean Circulation,Buoy Position Oceans,Ocean Circulation,Water Masses Oceans,Ocean Temperature",1,
            " Oceans,Ocean Circulation Oceans,Ocean Circulation,Thermohaline Circulation Oceans,Ocean Circulation,Water Masses",1,
            " Oceans,Ocean Circulation,Advection",1,
            " Oceans,Ocean Circulation,Ocean Currents Cryosphere,Glaciers/Ice Sheets,Icebergs Cryosphere,Glaciers/Ice Sheets",1,
            " Oceans,Ocean Circulation,Ocean Currents Oceans,Ocean Temperature,Water Temperature Biosphere,Aquatic Ecosystems,Plankton Oceans,Ocean Chemistry,Nutrients",1,
            " Oceans,Ocean Circulation,Water Masses",1,
            " Oceans,Ocean Optics,Gelbstoff Oceans,Salinity/Density,Conductivity Oceans,Salinity/Density,Density Oceans,Ocean Temperature,Water Temperature Oceans,Ocean Optics,Scattering Oceans,Salinity/Density,Salinity Oceans,Ocean Optics,Fluorescence",1,
            " Oceans,Ocean Temperature Atmosphere,Atmospheric Temperature,Air Temperature Oceans,Sea Ice,Ice Temperature Climate Indicators,Cryospheric Indicators,Snow Depth Cryosphere,Sea Ice,Ice Temperature Cryosphere,Sea Ice,Ice Growth/Melt",1,
            " Oceans,Ocean Temperature,Water Temperature Oceans,Salinity/Density",1,
            " Oceans,Salinity/Density,Density Oceans,Ocean Temperature,Water Temperature Oceans,Ocean Chemistry,Nutrients Oceans,Ocean Chemistry,Pigments,Chlorophyll Oceans,Salinity/Density,Salinity",1,
            " Solid Earth,Geochemistry,Geochemical Properties,Isotope Measurements",1,
            " Solid Earth,Geomorphic Landforms/Processes,Fluvial Landforms,Stream",1,
            " Terrestrial Hydrosphere,Snow/Ice,Ice Growth/Melt Cryosphere,Glaciers/Ice Sheets,Glacier Mass Balance/Ice Sheet Mass Balance",1,
            " Terrestrial Hydrosphere,Snow/Ice,Snow Melt Terrestrial Hydrosphere,Surface Water,Water Depth Atmosphere,Atmospheric Temperature,Air Temperature Biosphere,Ecological Dynamics,Species/Population Interactions,Population Dynamics Biological Classification,Animals/Vertebrates,Mammals,Carnivores Biosphere,Ecological Dynamics,Species/Population Interactions,Species Predation Biological Classification,Animals/Vertebrates,Birds Biological Classification,Animals/Invertebrates,Arthropods Biosphere,Ecological Dynamics,Species/Population Interactions,Species Life History Biological Classification,Animals/Vertebrates,Mammals,Rodents Atmosphere,Precipitation,Precipitation Amount Biological Classification,Animals/Vertebrates,Birds,Sandpipers Atmosphere,Atmospheric Winds,Surface Winds,Wind Speed/Wind Direction Biosphere,Ecological Dynamics,Species/Population Interactions,Survival Rates",1,
            " Terrestrial Hydrosphere,Surface Water,Lakes",1,
            " Agriculture,Soils,Permafrost",0,
            " Atmosphere,Aerosols,Particulate Matter Cryosphere,Glaciers/Ice Sheets,Firn Atmosphere,Air Quality,Emissions Atmosphere,Precipitation,Snow Atmosphere,Aerosols,Dust/Ash/Smoke Paleoclimate,Ice Core Records,Isotopes Atmosphere,Air Quality,Lead Paleoclimate,Ice Core Records,Particulate Matter Cryosphere,Snow/Ice,Snow/Ice Chemistry Atmosphere,Atmospheric Chemistry,Trace Elements/Trace Metals Atmosphere,Air Quality,Particulates Cryosphere,Glaciers/Ice Sheets,Glaciers",0,
            " Atmosphere,Air Quality,Nitrogen Oxides",0]},
        "facet_dates":{},
        "facet_ranges":{},
        "facet_intervals":{}
    }
};

var newJson = '{"' + min + '": {';
var i = 0;
while (i < min_year_data.facet_counts.facet_fields.science_keywords_s.length) {
    if (min_year_data.facet_counts.facet_fields.science_keywords_s[i] !== undefined) {
       newJson += '"' + min_year_data.facet_counts.facet_fields.science_keywords_s[i++] + '": ' + min_year_data.facet_counts.facet_fields.science_keywords_s[i++] + ', ';
    }
    else {
        i += 2;
    }
}
newJson = newJson.replace(/,\s*$/, "") + '}, "' + max + '": {';

i = 0;
while (i < max_year_data.facet_counts.facet_fields.science_keywords_s.length) {
    if (max_year_data.facet_counts.facet_fields.science_keywords_s[i] !== undefined) {
       newJson += '"' + max_year_data.facet_counts.facet_fields.science_keywords_s[i++] + '": ' + max_year_data.facet_counts.facet_fields.science_keywords_s[i++] + ', ';
    }
    else {
        i += 2;
    }
}
newJson = newJson.replace(/,\s*$/, "") + '}}';
console.log(JSON.parse(newJson));
all_data = JSON.parse(newJson);
min_year = min;
max_year = max;
//var my_data = '{"' + min + '": ' + +
//    +'}';
